export const PROFILE_SEARCH_REQUEST = 'PROFILE_SEARCH_REQUEST';
export const PROFILE_SEARCH_SUCCESS = 'PROFILE_SEARCH_SUCCESS';
export const PROFILE_SEARCH_FAIL = 'PROFILE_SEARCH_FAIL';
export const PROFILE_SEARCH_RESET = 'PROFILE_SEARCH_RESET';

export const PROFILE_LIST_REQUEST = 'PROFILE_LIST_REQUEST';
export const PROFILE_LIST_SUCCESS = 'PROFILE_LIST_SUCCESS';
export const PROFILE_LIST_FAIL = 'PROFILE_LIST_FAIL';
export const PROFILE_LIST_RESET = 'PROFILE_LIST_RESET';

export const PROFILE_ADD_FRIEND_REQUEST = 'PROFILE_ADD_FRIEND_REQUEST';
export const PROFILE_ADD_FRIEND_SUCCESS = 'PROFILE_ADD_FRIEND_SUCCESS';
export const PROFILE_ADD_FRIEND_FAIL = 'PROFILE_ADD_FRIEND_FAIL';
export const PROFILE_ADD_FRIEND_RESET = 'PROFILE_ADD_FRIEND_RESET';

export const PROFILE_GET_FRIENDS_REQUEST = 'PROFILE_GET_FRIENDS_REQUEST';
export const PROFILE_GET_FRIENDS_SUCCESS = 'PROFILE_GET_FRIENDS_SUCCESS';
export const PROFILE_GET_FRIENDS_FAIL = 'PROFILE_GET_FRIENDS_FAIL';
export const PROFILE_GET_FRIENDS_RESET = 'PROFILE_GET_FRIENDS_RESET';
